[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "vite" # Comando para iniciar o servidor de desenvolvimento
  targetPort = 5173 # Porta onde o Vite corre

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions" # Define explicitamente o diretório das funções

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; img-src 'self' data: https://image.tmdb.org https://via.placeholder.com https://walter.trakt.tv https://*.trakt.tv; connect-src 'self'; frame-src https://www.youtube.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; manifest-src 'self'; worker-src 'self' blob:"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"

# Redireciona os pedidos de API para as Netlify Functions
[[redirects]]
  from = "/api/tmdb/*"
  to = "/.netlify/functions/tmdb/:splat"
  status = 200

[[redirects]]
  from = "/api/trakt/*"
  to = "/.netlify/functions/trakt/:splat"
  status = 200
